### ISSUE TITLE
Whats happening with the db?

### ISSUE THREAD

**Issue by DanEvans485** [G-Bro/OpenDM-Server#25]
We did discuss this but do we have a planned structure yet?

**Comment by G-Bro** [comment]
Not yet. I was planning to start mapping it all out later today

**Comment by DanEvans485** [comment]
I will see if I can decipher when we said yesterday and update that chart I know you wanted to split monsters and characters but it should still work.

**Comment by Newobc** [comment]
duplicate of #14
