### ISSUE TITLE
Item actions

### ISSUE THREAD

**Issue by G-Bro** [G-Bro/OpenDM-Server#29]
In addition to modifiers, items have actions

Examples:

* A longsword grants the attack action of a 1d8 slashing damage
* A greatsword grants the attack action of 2d6 slashing damage
* A potion of healing grants the heal action of 2d4 + 2
* Ring of the ram grants the attack action of 2d10 force damage with +7 to the attack roll. This also pushes the enemy 5 feet away and the ring only has 3 charges, regaining 1-3 charges each day.

Note that the attack roll bonus for weapons is your proficiency bonus plus your strength modifier (or your dexterity modifier for finesse weapons if your dex is greater than your strength)

So I believe that items should have a 1 to many link to actions (some items grant several options)

| item_id | action_type | dice_id | dice_count | action_bonus | roll_bonus | description | consumes_item |  damage_type_id  |
|-------|-------------|--|--|--|--|--|--|--|
| 1 | attack | 3 | 1 | 0 | 0 | null | false | 2 |
| 2 | attack | 2 | 2 | 0 | 0 | null | false | 2 |
| 3 | heal | 1 | 2 | 2 | 0 | null | true | null |
| 4 | attack | 4 | 2 | 0 | 7 | On success, move target back 5 feet. | false | 6 |

I'm not sure how best to handle the charges that some items have

Actions can also be attached to spells (which I think are distinct from items) and races/classes among others  (probably)

**Comment by DanEvans485** [comment]
Charges can be ammunition? Have a requires ammunition on the item and a join table ItemAmmuntion which has a type_id and quantity.

**Comment by G-Bro** [comment]
Yup, that works 😁

**Comment by G-Bro** [comment]
Also, some actions are a bit different, like:

multiattack: the [character] makes two [action] attacks

So in the case of a Fire Giant they have the following actions:

Multiattack. The giant makes two greatsword attacks.
Greatsword. Melee weapon attack. +11 to hit, reach 10ft, one target. Hit 6d6 + 7 slashing damage
Rock. Ranged weapon attack. +11 to hit. range 60/240ft, one target. Hit 4d10 + 7 bludgeoning damage

**Comment by DanEvans485** [comment]
Because ofc they are

**Comment by DanEvans485** [comment]
Would a `count` column on action work for multi attacks? 99% of cases it'd be 1.

**Comment by G-Bro** [comment]
Yeah, I was thinking something like that.

Here are some other examples of actions:

Battle Cry (once per day). Each creature of the war chief's choice that is within 30 feet of it, can hear it, and is not already affected by Battle Cry gains advantage on attack rolls until the start of the war chief's next turn. The war chief can then make one attack as a bonus action.

Reel. The roper pulls each creature grappled by it up to 25ft straight toward it.

Terrifying glare. The scarecrow targets one creature it can see within 30 feet of it. If the target can see the scarecrow, the target must succeed on a DC 11 Wisdom saving throw or be magically frightened until the end of the scarecrow's next turn. The frightened target is paralyzed.

Stuff like this can probably be purely text based and its up to the DM to implement those rules. Perhaps their action type could be 'unique'?
