### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by G-Bro** [G-Bro/OpenDM-Server#3]
Some things are going to be User specific

For example, users can create custom monsters and create campaigns

We need some way of authenticating users. Laravel's built-in auth will probably suffice. Haven't looked into it enough

**Comment by Newobc** [comment]
I can do this @G-Bro.

I setup a project with two Auth recently, a core user Auth, and a token based API authentication for authenticating devices with a static token.

You can set up multiple password type authentications, but I'm not really clear on what the other _thing_ you're trying to authenticate is?

**Comment by DanEvans485** [comment]
Wouldn't it just be permissions? Which is separate from auth

**Comment by DanEvans485** [comment]
like: `player` permission and `dm` permission

**Comment by G-Bro** [comment]
But I'm picturing this being a platform. There can be multiple DMs running multiple campaigns, each one creating different monsters that only they can see

**Comment by G-Bro** [comment]
Essentially we need to be able to say "this monster belongs to this user"

**Comment by DanEvans485** [comment]
I imagined something like:
You can login as a user.
You can then create a campaign / level and select monsters from the db (or create new ones) then invite players.

**Comment by DanEvans485** [comment]
permissions would be relation between campaign and user

**Comment by G-Bro** [comment]
Yeah, so then you need to authenticate the user so that someone else can't come along and delete their shit

**Comment by DanEvans485** [comment]
Maybe you can "share" monsters / campaigns else they are linked to a specific user

**Comment by G-Bro** [comment]
Makes sense. So I guess in that case we need a many to many monsters_users table and monsters can have a share URL on them. If someone opens the monster's share URL then the monster gets linked to their user.

If someone deletes the monster it detaches it from their user. If no more users are attached to the monster then the server rolls a nat 20 and deletes that bitch

**Comment by Newobc** [comment]
So you just from this issue want the basic auth scaffolding?

Shouldn't take long to set up, even less if you're using the UI scaffolding as well?

**Comment by G-Bro** [comment]
Sounds good to me

**Comment by Newobc** [comment]
Feel free to assign me 👍

**Comment by G-Bro** [comment]
@Newobc I have sent you an invite to become a collaborator, which I assume grants you more permissions in this repo.

@DanEvans485 I did the same for you.

Presumably the invite was emailed to you or appears in your github dashboardy area

**Comment by Newobc** [comment]
I am joined. TY!
