### ISSUE TITLE
Monster extends <BaseClass>

### ISSUE THREAD

**Issue by G-Bro** [G-Bro/OpenDM-Server#4]
Monsters and Characters share a lot of attributes, such as calculating ability scores from ability modifiers and being able to use weapons, armour, having senses and languages etc.

Everything shared between the two classes should be in a base class or in traits

Monster extends BaseCharacter
Character extends BaseCharacter

**Comment by DanEvans485** [comment]
Sounds like JavaScript

**Comment by DanEvans485** [comment]
Would suggest maybe something like:
```js
class Character {}
class Player extends Character {}
class Monster extends Character {}
class Npc extends Character {}
```

**Comment by G-Bro** [comment]
Yeah I did think something like that, but I think Players and NPCs are probably going to be identical except that the Player character belongs to a Player user and an NPC belongs to the DM.

It does make the most sense though, so probably will go with that 👍
