### ISSUE TITLE
Docker config

### ISSUE THREAD

**Issue by DanEvans485** [G-Bro/OpenDM-Server#7]
Because I don't have php, node or anything else installed and I want to use it.

**Comment by G-Bro** [comment]
![image](https://user-images.githubusercontent.com/17454235/73972724-39be3c00-4919-11ea-91ec-9d62e9277c1a.png)

**Comment by DanEvans485** [comment]
![chrome_kTXTcV92BB](https://user-images.githubusercontent.com/29194430/73972898-7d18aa80-4919-11ea-8676-c70f265cb911.png)

**Comment by DanEvans485** [comment]
What db is this using?

**Comment by G-Bro** [comment]
phpmyadmin, db name is opendb

**Comment by DanEvans485** [comment]
So mysql

**Comment by G-Bro** [comment]
yeah, thats what I meant

I was about to ninja edit before you saw my mistake, but now I feel great shame

**Comment by DanEvans485** [comment]
You rolled a 1. And missed

**Comment by Newobc** [comment]
I think we can agree best let @DanEvans485 handle the Docker config lol.

I will contribute when thats started, because like @DanEvans485 , I have nothing installed except Docker. 😆

**Comment by G-Bro** [comment]
So jealous of @DanEvans485. He gets to solve docker issues at work and in his spare time 😩

**Comment by DanEvans485** [comment]
Whoo

Looks like a me problem

**Comment by G-Bro** [comment]
Looks like a you _solution_
